### ISSUE TITLE
Plans to publish runner to nixpkg?

### ISSUE THREAD

**Issue by scotttrinh** [patchgirl/patchgirl#19]
I currently run nix instead of Homebrew on my macOS machine, and would love to be able to install the runner with nix. Since you seem to be very familiar with nix, any plans on publishing to nixpkg?

**Comment by matsumonkie** [comment]
Hello @scotttrinh, as of now I don't have the time to setup patchgirl-runner for Nix on MacOS unfortunately :-(
It's definitely in my roadmap sometime this year but in the meantime I have a (not up to date) homebrew repo. I could update it for you if you feel like trying it :-)

Keep me posted!
